/* eslint-disable */
// @ts-nocheck
// generated by 'actions-kit'

import type * as core from "@actions/core";

declare global {
  export const ACTION_INPUTS = {
    "token": "token",
    "registry": "registry",
    "extension-path": "extension-path",
    "debug": "debug",
    "dry-run": "dry-run",
    "pre-release": "pre-release",
    "manager": "manager",
    "fail-silently": "fail-silently",
    "targets": "targets",
    "base-content-url": "base-content-url",
    "base-images-url": "base-images-url",
  };

  export const ACTION_OUTPUTS = {
    "vsix": "vsix",
    "success": "success",
  };

}

declare module "@actions/core" {

  type ActionInputName = "token" | "registry" | "extension-path" | "debug" | "dry-run" | "pre-release" | "manager" | "fail-silently" | "targets" | "base-content-url" | "base-images-url";

  export function getInput(name: ActionInputName, options?: core.InputOptions): string;

  type ActionOutputName = "vsix" | "success";

  export function setOutput(name: ActionOutputName, value: any): void;
}
