// generated by 'actions-kit'
        import "@actions/core";

        
declare global {
  export const ACTION_INPUTS: {
  "token": "token",
  "registry": "registry",
  "extension-path": "extension-path",
  "debug": "debug",
  "dry-run": "dry-run",
  "pre-release": "pre-release",
  "manager": "manager",
  "fail-silently": "fail-silently",
  "targets": "targets",
  "base-content-url": "base-content-url",
  "base-images-url": "base-images-url"
};
}

declare module "@actions/core" {

  type InputNames = "token" | "registry" | "extension-path" | "debug" | "dry-run" | "pre-release" | "manager" | "fail-silently" | "targets" | "base-content-url" | "base-images-url";

  export function getInput(name: InputNames, options?: InputOptions): string;
}
