name: "Publish VS Code Extension"
description: "An action to publish Visual Studio Code Extension to Open VSX Registry or Visual Studio Marketplace"

author: luxass
branding:
  color: purple
  icon: package

inputs:
  token:
    description: "The token to use for authentication."
    required: true

  registry:
    description: "The registry to publish to."
    required: true
    default: 'vsce'
    options:
      - 'vsce'
      - 'ovsx'
  
  extensionPath:
    description: "Path to VSIX File you want to publish."
    required: false
  
  debugVSIXFile:
    description: "List of files in the VSIX package, for debugging purposes."
    required: false
    default: false
  
  noPublish:
    description: "Do not publish the extension."
    required: false
    default: false
  
  preRelease:
    description: "Mark the extension as pre-release extension."
    required: false
    default: false
    
runs:
  using: "node16"
  main: "dist/index.js"
