// generated by 'actions-kit'
import "@actions/core";

export const inputs = {
"token": "token",
"registry": "registry",
"extension-path": "extension-path",
"debug": "debug",
"dry-run": "dry-run",
"pre-release": "pre-release",
"manager": "manager",
"fail-silently": "fail-silently",
"targets": "targets",
"base-content-url": "base-content-url",
"base-images-url": "base-images-url"
} as const;

declare module "@actions/core" {
  export const inputs: typeof coreInputs;
  type InputNames = "token" | "registry" | "extension-path" | "debug" | "dry-run" | "pre-release" | "manager" | "fail-silently" | "targets" | "base-content-url" | "base-images-url";

  export function getInput(name: InputNames, options?: InputOptions): string;
}

// biome-ignore lint/suspicious/noExplicitAny: <explanation>
(coreInputs as any) = inputs;
